#ifndef INCLUDED_kernel_colors_h
#define INCLUDED_kernel_colors_h


#define __COLOR_BLACK "0"
#define __COLOR_RED "1"
#define __COLOR_GREEN "2"
#define __COLOR_YELLOW "3"
#define __COLOR_BLUE "4"
#define __COLOR_MAGENTA "5"
#define __COLOR_CYAN "6"
#define __COLOR_WHITE "7"
#define __ANSI_COLOR_START "\x1b["
#define __ANSI_COLOR_FG "3"
#define __ANSI_COLOR_BG "4"
#define __ANSI_COLOR_END "m"

#define C_FG_BLACK __ANSI_COLOR_START __ANSI_COLOR_FG __COLOR_BLACK __ANSI_COLOR_END
#define C_FG_RED __ANSI_COLOR_START __ANSI_COLOR_FG __COLOR_RED __ANSI_COLOR_END
#define C_FG_GREEN __ANSI_COLOR_START __ANSI_COLOR_FG __COLOR_GREEN __ANSI_COLOR_END
#define C_FG_YELLOW __ANSI_COLOR_START __ANSI_COLOR_FG __COLOR_YELLOW __ANSI_COLOR_END
#define C_FG_BLUE __ANSI_COLOR_START __ANSI_COLOR_FG __COLOR_BLUE __ANSI_COLOR_END
#define C_FG_MAGENTA __ANSI_COLOR_START __ANSI_COLOR_FG __COLOR_MAGENTA __ANSI_COLOR_END
#define C_FG_CYAN __ANSI_COLOR_START __ANSI_COLOR_FG __COLOR_CYAN __ANSI_COLOR_END
#define C_FG_WHITE __ANSI_COLOR_START __ANSI_COLOR_FG __COLOR_WHITE __ANSI_COLOR_END

#define C_BG_BLACK __ANSI_COLOR_START __ANSI_COLOR_BG __COLOR_BLACK __ANSI_COLOR_END
#define C_BG_RED __ANSI_COLOR_START __ANSI_COLOR_BG __COLOR_RED __ANSI_COLOR_END
#define C_BG_GREEN __ANSI_COLOR_START __ANSI_COLOR_BG __COLOR_GREEN __ANSI_COLOR_END
#define C_BG_YELLOW __ANSI_COLOR_START __ANSI_COLOR_BG __COLOR_YELLOW __ANSI_COLOR_END
#define C_BG_BLUE __ANSI_COLOR_START __ANSI_COLOR_BG __COLOR_BLUE __ANSI_COLOR_END
#define C_BG_MAGENTA __ANSI_COLOR_START __ANSI_COLOR_BG __COLOR_MAGENTA __ANSI_COLOR_END
#define C_BG_CYAN __ANSI_COLOR_START __ANSI_COLOR_BG __COLOR_CYAN __ANSI_COLOR_END
#define C_BG_WHITE __ANSI_COLOR_START __ANSI_COLOR_BG __COLOR_WHITE __ANSI_COLOR_END

#define C_RESET __ANSI_COLOR_START "0" __ANSI_COLOR_END

#endif